### ISSUE TITLE
Remotes and Modules listing

### ISSUE THREAD

**Issue by schirrel** [module-federation/enhanced#1]
Based on [this](https://github.com/module-federation/module-federation-examples/issues/1323) issue and [this](https://github.com/schirrel/ModuleFederationEnhacedPlugin) code, turn available the list of the remotes being used, the modules being exported and the link of the remotes.

**Comment by prasannamestha** [comment]
I like the idea of autogenerating `remoteUrlMap` . @ScriptedAlchemy is there a way we could expose this to `ModuleFederationPlugin._options` ?
