### ISSUE TITLE
ENAMETOOLONG when using NX with module federation fails on 0.6.7+

### ISSUE THREAD

**Issue by nadavshatz** [module-federation/enhanced#16]
0.6.7 and 0.6.8 fail when using NX with module federation as can be seen in the following issues:
https://github.com/nrwl/nx/issues/28192
https://github.com/nrwl/nx/issues/28233

Happy to try and fix it if you have a hunch as to what it might be.

**Comment by Coly010** [comment]
This is the wrong repo, issue should be raised at https://github.com/module-federation/core
